### ISSUE TITLE
Can't create Jenkins Plugin project

### ISSUE THREAD

**Issue by ttimot24** [stapler/netbeans-stapler-plugin#2]
When I try to create Jenkins Plugin Project in NetBeans it always fails with this error:

Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: The desired archetype does not exist (org.jenkins-ci.tools:maven-hpi-plugin:LATEST) -> [Help 1]

**Comment by jglick** [comment]
I think you are using an old version of the plugin, predating https://github.com/stapler/netbeans-stapler-plugin/commit/fa0e49fff39b4d0b3032c71596d8e6471fffb7c2.
