### ISSUE TITLE
Plugin or Wiki need updating, cant create new plugin project

### ISSUE THREAD

**Issue by icojb25** [stapler/netbeans-stapler-plugin#3]
Hi, 
We need to develop a new plugin inhouse quite urgently, and this plugin for Netbeans seems to be out of date or the instructions on setting up settings.xml on the Wiki page need to be updated. 

Currently, even after quite a bit of googling, i have not been able to generate a working archetype to start working from. 

thanks and regards

Environment: Netbeans 8.2, Win 10

Settings.xml

<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

 <profiles>
   <profile>
     <id>jenkins</id>
     <activation>
       <activeByDefault>true</activeByDefault>
     </activation>
     <repositories>
       <repository>
         <id>java.net-m2-repository</id>
         <url>http://maven.jenkins-ci.org:8081/content/repositories/releases/
         </url>
       </repository>
     </repositories>
     <pluginRepositories>
       <pluginRepository>
         <id>jenkins-m2-repository</id>
         <name>Jenkins Plugin Repository</name>
         <url>http://maven.jenkins-ci.org:8081/content/repositories/releases/</url>
         <layout>default</layout>
       </pluginRepository>
     </pluginRepositories>
   </profile>
 </profiles>
 <pluginGroups>
   <pluginGroup>org.jenkins-ci.tools</pluginGroup>
 </pluginGroups>

</settings>

**Comment by jglick** [comment]
> i have not been able to generate a working archetype

Cannot help without an error message.

> Netbeans 8.2

The version of NetBeans is barely relevant. What mainly matters is the versions of the two plugins (**Stapler Support** and **Jenkins Plugin Support**).
